version: "3.7"
services:
  db: 
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
        default:
          aliases: 
            - database
    environment:
      MYSQL_ROOT_PASSWORD:  hmcr2020
    volumes:
      - ./db/data:/var/lib/mysql
  api:
      build: ./
      container_name: django-container
      stop_signal: SIGINT
      networks: 
        default:
          aliases: 
            - api
      volumes:
        - ./django:/usr/src/app
      ports:
        - "8000:8000"
  web:
    image: nginx
    container_name: nginx-container
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/
      - ../Frontend/dist/ss-web:/var/www
    networks: 
        default:
          aliases: 
            - web
    ports:
      - "8080:80"
      - "8181:81"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80